on:
  repository_dispatch:
    types: [frschool_e2e]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'branch name: ${{ github.event.client_payload.branch_name }}'"
      - name: Update repo commit status
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ github.event.client_payload.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.event.client_payload.repository }}/statuses/${{ github.event.client_payload.sha }} \
          -d '{"state":"success","context":"E2E tests","description":"Running E2E tests in the frs-testing repo","target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
