on:
  repository_dispatch:
    types: [frschool_e2e_local]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        # update postgres version together with version from dockerfile in frschool/db
        image: 'postgres:14'
        env:
          # needs to be kept in sync with frschool/e-learning/api/.env.example
          POSTGRES_USER: user
          POSTGRES_PASSWORD: testsomething
          POSTGRES_DB: elearning_api_postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.branch_name }}
          token: ${{ github.event.client_payload.github_token }}
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - run: PUPPETEER_SKIP_DOWNLOAD=true pnpm install
      - name: Install Playwright Browsers
        run: pnpm --filter @frsource/frschool-elearning-web exec playwright install --with-deps

      - uses: cardinalby/export-env-action@v2
        with:
          expand: true
          envFile: 'e-learning/api/.env.example'
      - uses: cardinalby/export-env-action@v2
        with:
          expand: true
          envFile: 'e-learning/web/.env.example'

      - name: Run E2E tests
        id: e2e_tests
        run: pnpm e2e:ci
      - name: Update repo commit status
        if: ${{ success() || failure() }}
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ github.event.client_payload.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.event.client_payload.repository }}/statuses/${{ github.event.client_payload.sha }} \
          -d '{"state": "${{ steps.e2e_tests.outcome == 'success' && 'success' || 'failure' }}","context":"E2E tests","description":"Running E2E tests in the frs-testing repo","target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'

      - name: upload artifacts from playwright tests
        uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: frschool-playwright-report
          path: e-learning/web/playwright-report/
          retention-days: 14
